version: 0.2
phases:
  pre_build:
    commands:
      - echo Install dependencies on `date`
      - yarn install
  build:
    commands:
      - echo Builder application started in `date`
      - yarn build
  post_build:
    commands:
      - echo Builder application finished in `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: app/build
